### ISSUE TITLE
如何将这些策略定义到别的管理组下？

### ISSUE THREAD

**Issue by angerfirecn** [sscchh2001/MooncakeCIS1_1_0#1]
如题，我看默认这些策略的生效位置是根管理组下。
![CIS](https://user-images.githubusercontent.com/74460945/108586545-28ac6580-738a-11eb-843d-8a867901ad1c.JPG)
如何定义到别的管理组下呢？

**Comment by sscchh2001** [comment]
deploy.ps1文件中 New-AzPolicySetDefinition 命令的 ManagementGroupName 参数定义了policy设置在哪个管理组下，把传进参数的变量改成其他管理组名就可以了。需要注意管理组名指的是管理组ID，不是显示名。
New-AzPolicySetDefinition `
    -Metadata '{"category": "Regulatory Compliance"}' `
    -Name $policySetName `
    -Description $policySetDesc `
    -DisplayName $policySetDisName `
    -PolicyDefinition policySetDef_withTenant.json `
    -Parameter policySetPara.json `
    -ManagementGroupName **$tenantID**
